#include "fastlint/rules/rules.h"
#include "testing/rule_tester.h"
#include "testing/test.h"

using namespace fastlint;

TEST(rules_no_constant_condition, cases)
{
  const char *none = R"([{"checkLoops": "none"}])";
  const char *all = R"([{"checkLoops": "all"}])";
  test::runRuleTests(
      rules::kNoConstantCondition,
      {
          {"if(a);"},
          {"if(a == 0);"},
          {"if(a = f());"},
          {"if(1, a);"},
          {"if ('every' in []);"},
          {"if (`\\\n${a}`) {}"},
          {"if (`${a}`) {}"},
          {"if (`${a}${b}`) {}"},
          {"while(~!a);"},
          {"while(a = b);"},
          {"while(typeof a == 'string' || a);"},
          {"for(;x < 10;);"},
          {"for(;;);"},
          {"for(;x;);"},
          {"do{ }while(x)"},
          {"q > 0 ? 1 : 2;"},
          {"`${a}` === a ? 1 : 2"},
          {"if(x === 0);"},
          {"if(x === 0 || x === 1);"},
          {"if(typeof x === 'undefined'){}"},
          {"if(`${typeof x}` === 'undefined'){}"},
          {"if(a === 'str' && typeof b){}"},
          {"typeof a === 'a' ? 1 : 2"},
          {"if(void a || a);"},
          {"if(x || a);"},
          {"if(a && true);"},
          {"if(false || a);"},
          {"if(a === b || 1 === c);"},
          {"if(Boolean(a));"},
          {"if(Boolean(...a));"},
          {"var undefined; if(undefined);"},
          {"while(true);"},
          {"while (true) {}"},
          {"while(true);", none},
          {"while(1);", none},
          {"for(;true;);", none},
          {"do{}while(true)", none},
          {"function* foo(){while(true){yield 'foo';}}", all},
          {"function* foo(){for(;true;){yield 'foo';}}", all},
          {"function* foo(){do{yield 'foo';}while(true)}", all},
          {"function* foo(){while (true) { while(true) {yield;}}}", all},
          {"function* foo() { for (let x = yield; x < 10; x++) { yield; } }"},
          {"if (a) { while(x) {} }"},
          {"if((a || b) && x);"},
          {"if(a ??= true);"},
          {"if(a ||= false);"},
          {"if(a &&= true);"},
          {"if((a || b) ??= 1);"},
      },
      {
          {"for(;true;);",
           {{"unexpected", 1, 6, 1, 10, "Unexpected constant condition."}}},
          {"if(new Boolean(a));", {{"unexpected"}}},
          {"for(;``;);", {{"unexpected"}}},
          {"for(;`foo`;);", {{"unexpected"}}},
          {"for(;`foo${bar}`;);", {{"unexpected"}}},
          {"do{}while(true)", {{"unexpected", 1, 11, 1, 15}}},
          {"do{}while('1')", {{"unexpected"}}},
          {"do{}while(0)", {{"unexpected"}}},
          {"do{}while(t = -2)", {{"unexpected"}}},
          {"do{}while(``)", {{"unexpected"}}},
          {"true ? 1 : 2;", {{"unexpected", 1, 1, 1, 5}}},
          {"1 ? 1 : 2;", {{"unexpected"}}},
          {"q = 0 ? 1 : 2;", {{"unexpected"}}},
          {"(q = 0) ? 1 : 2;", {{"unexpected"}}},
          {"`` ? 1 : 2;", {{"unexpected"}}},
          {"`foo` ? 1 : 2;", {{"unexpected"}}},
          {"`foo${bar}` ? 1 : 2;", {{"unexpected"}}},
          {"if(-2);", {{"unexpected", 1, 4, 1, 6}}},
          {"if(true);", {{"unexpected", 1, 4, 1, 8}}},
          {"if(1);", {{"unexpected"}}},
          {"if({});", {{"unexpected"}}},
          {"if(0 || 1);", {{"unexpected"}}},
          {"if(a, 1);", {{"unexpected"}}},
          {"if(`foo`);", {{"unexpected"}}},
          {"if(``);", {{"unexpected"}}},
          {"if(`\\\n`);", {{"unexpected"}}},
          {"if(`${'bar'}`);", {{"unexpected"}}},
          {"if(`${'bar' + `foo`}`);", {{"unexpected"}}},
          {"if(`foo${false || true}`);", {{"unexpected"}}},
          {"if(`foo${0 || 1}`);", {{"unexpected"}}},
          {"if(`foo${bar}`);", {{"unexpected"}}},
          {"if(`${bar}foo`);", {{"unexpected"}}},
          {"if(!(true || a));", {{"unexpected"}}},
          {"if(!(a && void b && c));", {{"unexpected"}}},
          {"if(0 || !(a && null));", {{"unexpected"}}},
          {"if(1 + !(a || true));", {{"unexpected"}}},
          {"if(!(null && a) > 1);", {{"unexpected"}}},
          {"if(+(!(a && 0)));", {{"unexpected"}}},
          {"if(!typeof a === 'string');", {{"unexpected"}}},
          {"if(-('foo' || a));", {{"unexpected"}}},
          {"if(+(void a && b) === ~(1 || c));", {{"unexpected"}}},
          {"if(a ||= true);", {{"unexpected"}}},
          {"if(a ||= 5);", {{"unexpected"}}},
          {"if(a ||= 'foo' || b);", {{"unexpected"}}},
          {"if(a ||= b || /regex/);", {{"unexpected"}}},
          {"if(a ||= b ||= true);", {{"unexpected"}}},
          {"if(a ||= b ||= c || 1);", {{"unexpected"}}},
          {"if(a &&= false);", {{"unexpected"}}},
          {"if(a &&= null);", {{"unexpected"}}},
          {"if(a &&= void b);", {{"unexpected"}}},
          {"if(a &&= 0 && b);", {{"unexpected"}}},
          {"if(a &&= b &&= false);", {{"unexpected"}}},
          {"if(a &&= b &&= c && false);", {{"unexpected"}}},
          {"if(a ||= 0 || b || 1);", {{"unexpected"}}},
          {"if(a &&= b && 1 && false);", {{"unexpected"}}},
          {"if(x = 1);", {{"unexpected"}}},
          {"if(x = {});", {{"unexpected"}}},
          {"if(x = []);", {{"unexpected"}}},
          {"if(x = -1);", {{"unexpected"}}},
          {"if(x = y = 1);", {{"unexpected"}}},
          {"if(x = y = true);", {{"unexpected"}}},
          {"if(void x);", {{"unexpected"}}},
          {"if(typeof x);", {{"unexpected"}}},
          {"if((x = typeof y));", {{"unexpected"}}},
          {"if(new Foo());", {{"unexpected"}}},
          {"if(a && '');", {{"unexpected"}}},
          {"if(a && 0);", {{"unexpected"}}},
          {"if(a && false);", {{"unexpected"}}},
          {"if(a && null);", {{"unexpected"}}},
          {"if(a && void b);", {{"unexpected"}}},
          {"if(undefined);", {{"unexpected"}}},
          {"if(Boolean(1));", {{"unexpected"}}},
          {"if(Boolean());", {{"unexpected"}}},
          {"if(Boolean([a]));", {{"unexpected"}}},
          {"if(Boolean(1));", {{"unexpected"}}},
          {"while(true);", {{"unexpected", 1, 7, 1, 11}}, nullptr, all},
          {"while(1);", {{"unexpected"}}},
          {"while('1');", {{"unexpected"}}},
          {"while(x = 1);", {{"unexpected"}}},
          {"while(-2);", {{"unexpected"}}},
          {"while([]);", {{"unexpected"}}},
          {"while(``);", {{"unexpected"}}},
          {"while(`foo`);", {{"unexpected"}}},
          {"while(`foo${bar}`);", {{"unexpected"}}},
          {"function* foo(){while(true){} yield 'foo';}", {{"unexpected"}}, nullptr, all},
          {"function* foo(){while(true){if (true) {yield 'foo';}}}",
           {{"unexpected"}},
           nullptr,
           all},
          {"function* foo(){while(true){yield 'foo';} while(true) {}}",
           {{"unexpected"}},
           nullptr,
           all},
          {"var a = function* foo(){while(true){} yield 'foo';}",
           {{"unexpected"}},
           nullptr,
           all},
          {"while (true) { function* foo() {yield;}}", {{"unexpected"}}, nullptr, all},
          {"function* foo(){if (true) {yield 'foo';}}", {{"unexpected"}}},
          {"function* foo() {for (let foo = yield; true;) {}}",
           {{"unexpected"}},
           nullptr,
           all},
          {"function* foo() {for (foo = yield; true;) {}}",
           {{"unexpected"}},
           nullptr,
           all},
          {"function foo() {while (true) {function* bar() {while (true) {yield;}}}}",
           {{"unexpected"}},
           nullptr,
           all},
          {"function foo() {while (true) {const bar = function*() {while (true) "
           "{yield;}}}}",
           {{"unexpected"}},
           nullptr,
           all},
          {"function* foo() { for (let foo = 1 + 2 + 3 + (yield); true; baz) {}}",
           {{"unexpected"}},
           nullptr,
           all},
          {"if(true); while(true) {}",
           {{"unexpected", 1, 4, 1, 8}, {"unexpected", 1, 17, 1, 21}},
           nullptr,
           all},
      });
}
