#include "fastlint/rules/rules.h"
#include "testing/rule_tester.h"
#include "testing/test.h"

using namespace fastlint;

TEST(rules_curly, cases)
{
  const char *multi = R"(["multi"])";
  const char *multiLine = R"(["multi-line"])";
  const char *multiOrNest = R"(["multi-or-nest"])";
  const char *multiConsistent = R"(["multi", "consistent"])";
  test::runRuleTests(
      rules::kCurly,
      {
          {"if (foo) { bar() }"},
          {"if (foo) { bar() } else if (foo2) { baz() }"},
          {"while (foo) { bar() }"},
          {"do { foo() } while (bar)"},
          {"for (;foo;) { bar() }"},
          {"for (var foo in bar) { console.log(foo) }"},
          {"for (var foo of bar) { console.log(foo) }"},
          {"if (foo) bar()", multi},
          {"if (foo) bar()\nelse baz()", multi},
          {"if (foo) { bar(); baz(); }", multi},
          {"for (;foo;) bar()", multi},
          {"while (foo) bar()", multi},
          {"do baz(); while (foo)", multi},
          {"if (foo) { let x = 1; }", multi},
          {"if (foo) { const x = 1; }", multi},
          {"if (foo) { function f() {} }", multi},
          {"if (foo) { class C {} }", multi},
          {"if (foo) { if (bar) baz(); } else qux()", multi},
          {"if (foo) bar()", multiLine},
          {"if (foo) bar()\nelse if (foo2) baz()\nelse qux()", multiLine},
          {"while (foo) bar()", multiLine},
          {"do foo(); while (bar)", multiLine},
          {"for (;foo;) bar()", multiLine},
          {"if (foo) {\n  bar();\n  baz();\n}", multiLine},
          {"if (foo) { bar() }", multiLine},
          {"if (foo) {\n bar();\n}", multiLine},
          {"if (foo) bar()", multiOrNest},
          {"if (foo) {\n  bar();\n  baz();\n}", multiOrNest},
          {"if (foo) {\n  bar(\n    1\n  );\n}", multiOrNest},
          {"if (foo) {\n  // comment\n  bar();\n}", multiOrNest},
          {"while (foo) bar()", multiOrNest},
          {"if (foo) bar(); else baz();", multiConsistent},
          {"if (foo) { bar(); baz(); } else { qux() }", multiConsistent},
          {"if (a) b; else if (c) d; else e;", multiConsistent},
          {"for (const x of y) {\n  a();\n  b();\n}", multiOrNest},
      },
      {
          {"if (foo) bar()",
           {{"missingCurlyAfterCondition",
             1,
             10,
             1,
             15,
             "Expected { after 'if' condition."}},
           "if (foo) {\n  bar()\n}"},
          {"if (foo) \n bar()",
           {{"missingCurlyAfterCondition"}},
           "if (foo) \n {\n   bar()\n }"},
          {"if (foo) bar(); else baz()",
           {{"missingCurlyAfterCondition"},
            {"missingCurlyAfter", 1, 22, 1, 27, "Expected { after 'else'."}},
           "if (foo) {\n  bar();\n} else {\n  baz()\n}"},
          {"if (foo) { bar() } else baz()",
           {{"missingCurlyAfter"}},
           "if (foo) { bar() } else {\n  baz()\n}"},
          {"if (foo) bar(); else if (baz) qux()",
           {{"missingCurlyAfterCondition"}, {"missingCurlyAfterCondition"}},
           "if (foo) {\n  bar();\n} else if (baz) {\n  qux()\n}"},
          {"while (foo) bar()",
           {{"missingCurlyAfterCondition",
             0,
             0,
             0,
             0,
             "Expected { after 'while' condition."}},
           "while (foo) {\n  bar()\n}"},
          {"do bar(); while (foo)",
           {{"missingCurlyAfter", 0, 0, 0, 0, "Expected { after 'do'."}},
           "do {\n  bar();\n} while (foo)"},
          {"for (;foo;) bar()",
           {{"missingCurlyAfterCondition",
             0,
             0,
             0,
             0,
             "Expected { after 'for' condition."}},
           "for (;foo;) {\n  bar()\n}"},
          {"for (var foo in bar) console.log(foo)",
           {{"missingCurlyAfter", 0, 0, 0, 0, "Expected { after 'for-in'."}},
           "for (var foo in bar) {\n  console.log(foo)\n}"},
          {"for (var foo of bar) console.log(foo)",
           {{"missingCurlyAfter", 0, 0, 0, 0, "Expected { after 'for-of'."}},
           "for (var foo of bar) {\n  console.log(foo)\n}"},
          {"if (foo) { bar(); }",
           {{"unexpectedCurlyAfterCondition",
             1,
             10,
             1,
             20,
             "Unnecessary { after 'if' condition."}},
           "if (foo) bar();",
           multi},
          {"if (foo) { bar() }", {{"unexpectedCurlyAfterCondition"}}, nullptr, multi},
          {"if (foo) { bar(); } else { baz(); }",
           {{"unexpectedCurlyAfterCondition"},
            {"unexpectedCurlyAfter", 0, 0, 0, 0, "Unnecessary { after 'else'."}},
           "if (foo) bar(); else baz();",
           multi},
          {"while (foo) { bar(); }",
           {{"unexpectedCurlyAfterCondition",
             0,
             0,
             0,
             0,
             "Unnecessary { after 'while' condition."}},
           "while (foo) bar();",
           multi},
          {"do { bar(); } while (foo)",
           {{"unexpectedCurlyAfter", 0, 0, 0, 0, "Unnecessary { after 'do'."}},
           "do bar(); while (foo)",
           multi},
          {"for (;foo;) { bar(); }",
           {{"unexpectedCurlyAfterCondition"}},
           "for (;foo;) bar();",
           multi},
          {"for (var foo in bar) { console.log(foo); }",
           {{"unexpectedCurlyAfter"}},
           "for (var foo in bar) console.log(foo);",
           multi},
          {"if (foo) { var x = 1; }",
           {{"unexpectedCurlyAfterCondition"}},
           "if (foo) var x = 1;",
           multi},
          {"if (foo) \n bar(); \n baz()",
           {{"missingCurlyAfterCondition"}},
           "if (foo) \n {\n   bar();\n } \n baz()",
           multiLine},
          {"if (foo) bar(1,\n 2)",
           {{"missingCurlyAfterCondition"}},
           "if (foo) {\n  bar(1,\n 2)\n}",
           multiLine},
          {"while (foo) \n bar()",
           {{"missingCurlyAfterCondition"}},
           "while (foo) \n {\n   bar()\n }",
           multiLine},
          {"if (foo) {\n bar();\n}",
           {{"unexpectedCurlyAfterCondition"}},
           "if (foo) bar();",
           multiOrNest},
          {"if (foo) bar(1,\n 2)",
           {{"missingCurlyAfterCondition"}},
           "if (foo) {\n  bar(1,\n 2)\n}",
           multiOrNest},
          {"while (foo) { bar(); }",
           {{"unexpectedCurlyAfterCondition"}},
           "while (foo) bar();",
           multiOrNest},
          // Under `consistent`, braces nobody needs come off every branch.
          {"if (foo) { bar(); } else baz();",
           {{"unexpectedCurlyAfterCondition"}},
           "if (foo) bar(); else baz();",
           multiConsistent},
          {"if (foo) bar(); else { baz(); }",
           {{"unexpectedCurlyAfter"}},
           "if (foo) bar(); else baz();",
           multiConsistent},
          {"if (foo) { bar() } else { baz() }",
           {{"unexpectedCurlyAfterCondition", 1, 10}, {"unexpectedCurlyAfter", 1, 25}},
           nullptr,
           multiConsistent},
          {"if (foo) { bar(); baz(); } else qux();",
           {{"missingCurlyAfter"}},
           "if (foo) { bar(); baz(); } else {\n  qux();\n}",
           multiConsistent},
          {"if (a) { b(); } else if (c) d(); else { e(); }",
           {{"unexpectedCurlyAfterCondition", 1, 8}, {"unexpectedCurlyAfter", 1, 39}},
           "if (a) b(); else if (c) d(); else e();",
           multiConsistent},
      });
}
