#include "fastlint/rules/rules.h"
#include "testing/rule_tester.h"
#include "testing/test.h"

using namespace fastlint;

TEST(rules_prefer_as_const, cases)
{
  test::runRuleTests(
      rules::kPreferAsConst,
      {
          {"let foo = 'baz' as const;"},
          {"let foo = 1 as const;"},
          {"let foo = { bar: 'baz' as const };"},
          {"let foo = { bar: 1 as const };"},
          {"let foo = { bar: 'baz' };"},
          {"let foo = { bar: 2 };"},
          {"let foo = <bar>'bar';"},
          {"let foo = <string>'bar';"},
          {"let foo = 'bar' as string;"},
          {"let foo = `bar` as `bar`;"},
          {"let foo = `bar` as `foo`;"},
          {"let foo = `bar` as 'bar';"},
          {"let foo: string = 'bar';"},
          {"let foo: number = 1;"},
          {"let foo: 'bar' = baz;"},
          {"let foo = 'bar';"},
          {"let foo: 'bar';"},
          {"let foo = { bar };"},
          {"let foo: 'baz' = 'baz' as const;"},
          {"class foo { bar = 'baz'; }"},
          {"class foo { bar: 'baz'; }"},
          {"class foo { bar; }"},
          {"class foo { bar = <baz>'baz'; }"},
          {"class foo { bar: string = 'baz'; }"},
          {"class foo { bar: number = 1; }"},
          {"class foo { bar = 'baz' as const; }"},
          {"class foo { bar = 2 as const; }"},
          {"class foo { get bar(): 'bar' {} set bar(bar: 'bar') {} }"},
          {"class foo { bar = () => 'bar' as const; }"},
          {"type BazFunction = () => 'baz'; class foo { bar: BazFunction = () => 'bar'; "
           "}"},
          {"class foo { bar(): void {} }"},
      },
      {
          {"let foo = { bar: 'baz' as 'baz' };",
           {{"preferConstAssertion",
             1,
             27,
             1,
             32,
             "Expected a `const` instead of a literal type assertion."}},
           "let foo = { bar: 'baz' as const };"},
          {"let foo = { bar: 1 as 1 };",
           {{"preferConstAssertion", 1, 23, 1, 24}},
           "let foo = { bar: 1 as const };"},
          {"let []: 'bar' = 'bar';", {{"variableConstAssertion", 1, 9, 1, 14}}},
          {"let foo: 'bar' = 'bar';",
           {{"variableConstAssertion",
             1,
             10,
             1,
             15,
             "Expected a `const` assertion instead of a literal type annotation."}}},
          {"let foo: 2 = 2;", {{"variableConstAssertion", 1, 10, 1, 11}}},
          {"let foo: 'bar' = 'bar' as 'bar';",
           {{"preferConstAssertion", 1, 27, 1, 32}},
           "let foo: 'bar' = 'bar' as const;"},
          {"let foo = <'bar'>'bar';",
           {{"preferConstAssertion", 1, 12, 1, 17}},
           "let foo = <const>'bar';"},
          {"let foo = <4>4;",
           {{"preferConstAssertion", 1, 12, 1, 13}},
           "let foo = <const>4;"},
          {"let foo = 'bar' as 'bar';",
           {{"preferConstAssertion", 1, 20, 1, 25}},
           "let foo = 'bar' as const;"},
          {"let foo = 5 as 5;",
           {{"preferConstAssertion", 1, 16, 1, 17}},
           "let foo = 5 as const;"},
          {"class foo { bar: 'baz' = 'baz'; }",
           {{"variableConstAssertion", 1, 18, 1, 23}}},
          {"class foo { bar: 2 = 2; }", {{"variableConstAssertion", 1, 18, 1, 19}}},
          {"class foo { foo = <'bar'>'bar'; }",
           {{"preferConstAssertion", 1, 20, 1, 25}},
           "class foo { foo = <const>'bar'; }"},
          {"class foo { foo = 'bar' as 'bar'; }",
           {{"preferConstAssertion", 1, 28, 1, 33}},
           "class foo { foo = 'bar' as const; }"},
          {"class foo { foo = 5 as 5; }",
           {{"preferConstAssertion", 1, 24, 1, 25}},
           "class foo { foo = 5 as const; }"},
      });
}
