#include "fastlint/rules/rules.h"
#include "testing/rule_tester.h"
#include "testing/test.h"

using namespace fastlint;

TEST(rules_array_type, cases)
{
  const char *array = R"([{"default": "array"}])";
  const char *generic = R"([{"default": "generic"}])";
  const char *simple = R"([{"default": "array-simple"}])";
  const char *arrayReadonlyGeneric = R"([{"default": "array", "readonly": "generic"}])";
  const char *genericReadonlyArray = R"([{"default": "generic", "readonly": "array"}])";
  test::runRuleTests(
      rules::kArrayType,
      {
          {"let a: number[] = [];", array},
          {"let a: (string | number)[] = [];", array},
          {"let a: readonly number[] = [];", array},
          {"let a: readonly (string | number)[] = [];", array},
          {"let a: number[] = [];", R"([{"default": "array", "readonly": "array"}])"},
          {"let a: readonly number[] = [];",
           R"([{"default": "array", "readonly": "array"}])"},
          {"let a: number[] = [];",
           R"([{"default": "array", "readonly": "array-simple"}])"},
          {"let a: readonly number[] = [];",
           R"([{"default": "array", "readonly": "array-simple"}])"},
          {"let a: ReadonlyArray<number> = [];", arrayReadonlyGeneric},
          {"let a: ReadonlyArray<string | number> = [];", arrayReadonlyGeneric},
          {"let a: number[] = [];", simple},
          {"let a: Array<string | number> = [];", simple},
          {"let a: readonly number[] = [];", simple},
          {"let a: ReadonlyArray<string | number> = [];", simple},
          {"let a: Array<number> = [];", generic},
          {"let a: Array<string | number> = [];", generic},
          {"let a: ReadonlyArray<number> = [];", generic},
          {"let a: ReadonlyArray<string | number> = [];", generic},
          {"let a: readonly number[] = [];",
           R"([{"default": "generic", "readonly": "array-simple"}])"},
          {"let a: Array<number> = [];", genericReadonlyArray},
          {"let a: readonly number[] = [];", genericReadonlyArray},
          {"let a: readonly (string | number)[] = [];", genericReadonlyArray},
          {"let a = new Array();", array},
          {"let a: { foo: Bar[] }[] = [];", array},
          {"function foo(a: Array<Bar>): Array<Bar> {}", generic},
          {"let yy: number[][] = [[4, 5], [6]];", array},
          {"function fooFunction(foo: Array<ArrayClass<string>>) { return foo.map(e => "
           "e.foo); }",
           generic},
          {"function bazFunction(baz: Arr<ArrayClass<String>>) { return baz.map(e => "
           "e.baz); }",
           generic},
          {"let fooVar: Array<(c: number) => number>;", generic},
          {"type fooUnion = Array<string | number | boolean>;", generic},
          {"type fooIntersection = Array<string & number>;", generic},
          {"namespace fooName { type BarType = { bar: string }; type BazType<T> = "
           "Arr<T>; }",
           generic},
          {"let z: Array = [3, '4'];", simple},
          {"let z: Array = [3, '4'];", array},
          {"let ya = [[1, '2']] as [number, string][];", array},
          {"type Arr<T> = Array<T>;", generic},
          {"type Foo = Array<keyof Bar>;", simple},
          {"let fooVar: Array<(c: number) => number>;", simple},
          {"type fooUnion = Array<string | number | boolean>;", simple},
          {"type fooIntersection = Array<string & number>;", simple},
          {"let x: Array<number> = [];",
           R"([{"default": "generic", "readonly": "generic"}])"},
          {"let a: number[] = [];",
           R"([{"default": "array-simple", "readonly": "generic"}])"},
          {"let a: readonly number[] = [];",
           R"([{"default": "array-simple", "readonly": "array"}])"},
          {"let a: ReadonlyArray<string | number> = [];",
           R"([{"default": "array-simple", "readonly": "array-simple"}])"},
          {"interface Array<T> { m(): T } let a: Array<number> = [];", array},
          {"type Readonly<T> = T; let a: Readonly<number[]> = [];", array},
          {"let a: Readonly<number> = 1;", array},
      },
      {
          {"let a: Array<number> = [];",
           {{"errorStringArray",
             1,
             8,
             1,
             21,
             "Array type using 'Array<number>' is forbidden. Use 'number[]' instead."}},
           "let a: number[] = [];",
           array},
          {"let a: Array<string | number> = [];",
           {{"errorStringArray",
             0,
             0,
             0,
             0,
             "Array type using 'Array<T>' is forbidden. Use 'T[]' instead."}},
           "let a: (string | number)[] = [];",
           array},
          {"let a: ReadonlyArray<number> = [];",
           {{"errorStringArray",
             0,
             0,
             0,
             0,
             "Array type using 'ReadonlyArray<number>' is forbidden. Use 'readonly "
             "number[]' instead."}},
           "let a: readonly number[] = [];",
           array},
          {"let a: ReadonlyArray<string | number> = [];",
           {{"errorStringArray",
             0,
             0,
             0,
             0,
             "Array type using 'ReadonlyArray<T>' is forbidden. Use 'readonly T[]' "
             "instead."}},
           "let a: readonly (string | number)[] = [];",
           array},
          {"let a: Readonly<number[]> = [];",
           {{"errorStringArrayReadonly",
             0,
             0,
             0,
             0,
             "Array type using 'Readonly<number[]>' is forbidden. Use 'readonly "
             "number[]' instead."}},
           "let a: readonly number[] = [];",
           array},
          {"let a: number[] = [];",
           {{"errorStringGeneric",
             1,
             8,
             1,
             16,
             "Array type using 'number[]' is forbidden. Use 'Array<number>' instead."}},
           "let a: Array<number> = [];",
           generic},
          {"let a: (string | number)[] = [];",
           {{"errorStringGeneric",
             0,
             0,
             0,
             0,
             "Array type using 'T[]' is forbidden. Use 'Array<T>' instead."}},
           "let a: Array<string | number> = [];",
           generic},
          {"let a: readonly number[] = [];",
           {{"errorStringGeneric",
             1,
             8,
             1,
             25,
             "Array type using 'readonly number[]' is forbidden. Use "
             "'ReadonlyArray<number>' instead."}},
           "let a: ReadonlyArray<number> = [];",
           generic},
          {"let a: readonly (string | number)[] = [];",
           {{"errorStringGeneric",
             0,
             0,
             0,
             0,
             "Array type using 'readonly T[]' is forbidden. Use 'ReadonlyArray<T>' "
             "instead."}},
           "let a: ReadonlyArray<string | number> = [];",
           generic},
          {"let a: Array<number> = [];",
           {{"errorStringArraySimple",
             0,
             0,
             0,
             0,
             "Array type using 'Array<number>' is forbidden for simple types. Use "
             "'number[]' instead."}},
           "let a: number[] = [];",
           simple},
          {"let a: (string | number)[] = [];",
           {{"errorStringGenericSimple",
             0,
             0,
             0,
             0,
             "Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' "
             "instead."}},
           "let a: Array<string | number> = [];",
           simple},
          {"let a: readonly (string | number)[] = [];",
           {{"errorStringGenericSimple",
             0,
             0,
             0,
             0,
             "Array type using 'readonly T[]' is forbidden for non-simple types. Use "
             "'ReadonlyArray<T>' instead."}},
           "let a: ReadonlyArray<string | number> = [];",
           simple},
          {"let a: ReadonlyArray<number> = [];",
           {{"errorStringArraySimple"}},
           "let a: readonly number[] = [];",
           simple},
          {"let a: readonly number[] = [];",
           {{"errorStringGeneric"}},
           "let a: ReadonlyArray<number> = [];",
           arrayReadonlyGeneric},
          {"let a: ReadonlyArray<number> = [];",
           {{"errorStringArray"}},
           "let a: readonly number[] = [];",
           genericReadonlyArray},
          {"let a: number[] = [];",
           {{"errorStringGeneric"}},
           "let a: Array<number> = [];",
           genericReadonlyArray},
          {"let x: Array<undefined> = [undefined] as undefined[];",
           {{"errorStringArray", 1, 8, 1, 24}},
           "let x: undefined[] = [undefined] as undefined[];",
           array},
          {"let y: string[] = <Array<string>>['2'];",
           {{"errorStringArray", 1, 20, 1, 33}},
           "let y: string[] = <string[]>['2'];",
           array},
          {"let ya = [[1, '2']] as [number, string][];",
           {{"errorStringGeneric",
             1,
             24,
             1,
             42,
             "Array type using 'T[]' is forbidden. Use 'Array<T>' instead."}},
           "let ya = [[1, '2']] as Array<[number, string]>;",
           generic},
          {"let xx: Array<Array<number>> = [[1, 2], [3]];",
           {{"errorStringArray", 1, 9, 1, 29}, {"errorStringArray", 1, 15, 1, 28}},
           "let xx: number[][] = [[1, 2], [3]];",
           array},
          {"let yy: number[][] = [[4, 5], [6]];",
           {{"errorStringGeneric", 1, 9, 1, 17}, {"errorStringGeneric", 1, 9, 1, 19}},
           "let yy: Array<Array<number>> = [[4, 5], [6]];",
           generic},
          {"function foo(a: Array<Bar>): Array<Bar> {}",
           {{"errorStringArray", 1, 17, 1, 27}, {"errorStringArray", 1, 30, 1, 40}},
           "function foo(a: Bar[]): Bar[] {}",
           array},
          {"let x: Array<number | string>[] = [];",
           {{"errorStringGeneric", 1, 8, 1, 32}},
           "let x: Array<Array<number | string>> = [];",
           generic},
          {"let x: Array<(() => void)> = [];",
           {{"errorStringArray"}},
           "let x: (() => void)[] = [];",
           array},
          {"let a: Array<typeof x> = [];",
           {{"errorStringArray"}},
           "let a: typeof x[] = [];",
           array},
          {"let a: Array<keyof T> = [];",
           {{"errorStringArray"}},
           "let a: (keyof T)[] = [];",
           array},
          {"let a: Array<A | B>[] = [];",
           {{"errorStringArray", 1, 8, 1, 20}},
           "let a: (A | B)[][] = [];",
           array},
          {"type Foo = ReadonlyArray<object>[];",
           {{"errorStringArray", 1, 12, 1, 33}},
           "type Foo = (readonly object[])[];",
           array},
          // The first pass gives `readonly (string | number)[]`; the fixpoint then
          // applies the readonly option to that.
          {"let a: readonly Array<string | number> = [];",
           {{"errorStringArray", 1, 17, 1, 39}},
           "let a: ReadonlyArray<string | number> = [];",
           R"([{"default": "array", "readonly": "array-simple"}])"},
          {"const x: Array<Array<string>> = [];",
           {{"errorStringArraySimple"}, {"errorStringArraySimple"}},
           "const x: string[][] = [];",
           simple},
          {"let a: Array<import('foo').T> = [];",
           {{"errorStringArray"}},
           "let a: import('foo').T[] = [];",
           array},
      });
}
