#include "fastlint/rules/rules.h"
#include "testing/rule_tester.h"
#include "testing/test.h"

using namespace fastlint;

// Codes begin with a newline so the line numbers match upstream's cases.

TEST(rules_no_shadow, typescript_cases)
{
  const char *typeValue = R"([{"ignoreTypeValueShadow": false}])";
  const char *keepTypeValue = R"([{"ignoreTypeValueShadow": true}])";
  const char *fnParam = R"([{"ignoreFunctionTypeParameterNameValueShadow": false}])";
  const char *keepFnParam = R"([{"ignoreFunctionTypeParameterNameValueShadow": true}])";
  const char *onInit = R"([{"ignoreOnInitialization": true}])";
  const char *builtins = R"([{"builtinGlobals": true}])";
  const char *hoistAll = R"([{"hoist": "all"}])";
  const char *hoistFunctions = R"([{"hoist": "functions"}])";
  const char *hoistTypes = R"([{"hoist": "types"}])";
  const char *hoistNever = R"([{"hoist": "never"}])";
  const char *hoistBoth = R"([{"hoist": "functions-and-types"}])";
  test::runRuleTests(
      rules::kNoShadow,
      {
          {"function foo<T = (arg: any) => any>(arg: T) {}"},
          {"function foo<T = ([arg]: [any]) => any>(arg: T) {}"},
          {"function foo<T = ({ args }: { args: any }) => any>(arg: T) {}"},
          {"function foo<T = (...args: any[]) => any>(fn: T, args: any[]) {}"},
          {"function foo<T extends (...args: any[]) => any>(fn: T, args: any[]) {}"},
          {"function foo<T extends (...args: any[]) => any>(fn: T, ...args: any[]) {}"},
          {"function foo<T extends ([args]: any[]) => any>(fn: T, args: any[]) {}"},
          {"function foo<T extends ([...args]: any[]) => any>(fn: T, args: any[]) {}"},
          {"function foo<T extends ({ args }: { args: any }) => any>(fn: T, args: any) "
           "{}"},
          {"\nfunction foo<T extends (id: string, ...args: any[]) => any>(\n  fn: T,\n  "
           "...args: any[]\n) {}"},
          {"\ntype Args = 1;\nfunction foo<T extends (Args: any) => void>(arg: T) {}"},
          {"\nexport type ArrayInput<Func> = Func extends (arg0: Array<infer T>) => "
           "any\n  ? "
           "T[]\n  : Func extends (...args: infer T) => any\n    ? T\n    : never;"},
          {"\nfunction foo() {\n  var Object = 0;\n}"},
          {"\nfunction test(this: Foo) {\n  function test2(this: Bar) {}\n}"},
          {"\nclass Foo {\n  prop = 1;\n}\nnamespace Foo {\n  export const v = 2;\n}"},
          {"\nfunction Foo() {}\nnamespace Foo {\n  export const v = 2;\n}"},
          {"\nclass Foo {\n  prop = 1;\n}\ninterface Foo {\n  prop2: string;\n}"},
          {"\nimport type { Foo } from 'bar';\ndeclare module 'bar' {\n  export "
           "interface Foo "
           "{\n    x: string;\n  }\n}"},
          {"\nconst x = 1;\ntype x = string;"},
          {"\nconst x = 1;\n{\n  type x = string;\n}"},
          {"\ntype Foo = 1;", keepTypeValue},
          {"\nenum Direction {\n  left = 'left',\n  right = 'right',\n}"},
          {"\nenum A {\n  B,\n  C,\n}"},
          {"\nenum A {\n  B,\n  C = A.B,\n}"},
          {"\nconst test = 1;\ntype Fn = (test: string) => typeof test;", keepFnParam},
          {"\nconst arg = 0;\ninterface Test {\n  (arg: string): typeof arg;\n}",
           keepFnParam},
          {"\nconst arg = 0;\ninterface Test {\n  p1(arg: string): typeof arg;\n}",
           keepFnParam},
          {"\nconst arg = 0;\ndeclare function test(arg: string): typeof arg;",
           keepFnParam},
          {"\nconst arg = 0;\ndeclare const test: (arg: string) => typeof arg;",
           keepFnParam},
          {"\nconst arg = 0;\ndeclare class Test {\n  p1(arg: string): typeof arg;\n}",
           keepFnParam},
          {"\nconst arg = 0;\ndeclare const Test: {\n  new (arg: string): typeof "
           "arg;\n};",
           keepFnParam},
          {"\nconst arg = 0;\ntype Bar = new (arg: number) => typeof arg;", keepFnParam},
          {"\nconst arg = 0;\ndeclare namespace Lib {\n  function test(arg: string): "
           "typeof "
           "arg;\n}",
           keepFnParam},
          {"\ndeclare global {\n  interface ArrayConstructor {}\n}\nexport {};",
           builtins},
          {"\ndeclare global {\n  const a: string;\n  namespace Foo {\n    const a: "
           "number;\n  "
           "}\n}\nexport {};"},
          {"\ndeclare global {\n  type A = 'foo';\n  namespace Foo {\n    type A = "
           "'bar';\n  "
           "}\n}\nexport {};",
           typeValue},
          {"\ndeclare global {\n  const foo: string;\n  type Fn = (foo: number) => "
           "void;\n}\nexport {};",
           fnParam},
          {"\nexport class Wrapper<Wrapped> {\n  private constructor(private readonly "
           "wrapped: "
           "Wrapped) {}\n  unwrap(): Wrapped {\n    return this.wrapped;\n  }\n  static "
           "create<Wrapped>(wrapped: Wrapped) {\n    return new "
           "Wrapper<Wrapped>(wrapped);\n  "
           "}\n}"},
          {"\nfunction makeA() {\n  return class A<T> {\n    constructor(public value: "
           "T) {}\n  "
           "  static make<T>(value: T) {\n      return new A<T>(value);\n    }\n  };\n}"},
          {"\nimport type { foo } from './foo';\ntype bar = number;\nfunction "
           "doThing(foo: "
           "number, bar: number) {}",
           keepTypeValue},
          {"\nimport { type foo } from './foo';\nfunction doThing(foo: number) {}",
           keepTypeValue},
          {"const a = [].find(a => a);", onInit},
          {"\nconst a = [].find(function (a) {\n  return a;\n});", onInit},
          {"const [a = [].find(a => true)] = dummy;", onInit},
          {"const { a = [].find(a => true) } = dummy;", onInit},
          {"function func(a = [].find(a => true)) {}", onInit},
          {"\nfor (const a in [].find(a => true)) {\n}", onInit},
          {"\nfor (const a of [].find(a => true)) {\n}", onInit},
          {"const a = [].map(a => true).filter(a => a === 'b');", onInit},
          {"\nconst a = []\n  .map(a => true)\n  .filter(a => a === 'b')\n  .find(a => a "
           "=== "
           "'c');",
           onInit},
          {"const { a } = (({ a }) => ({ a }))();", onInit},
          {"\nconst person = people.find(item => {\n  const person = item.name;\n  "
           "return "
           "person === 'foo';\n});",
           onInit},
          {"var y = bar || foo(y => y);", onInit},
          {"var y = bar && foo(y => y);", onInit},
          {"var z = bar(foo(z => z));", onInit},
          {"var z = boo(bar(foo(z => z)));", onInit},
          {"\nvar match = function (person) {\n  return person.name === "
           "'foo';\n};\nconst "
           "person = [].find(match);",
           onInit},
          {"const a = foo(x || (a => {}));", onInit},
          {"const { a = 1 } = foo(a => {});", onInit},
          {"const person = { ...people.find(person => person.firstName.startsWith('s')) "
           "};",
           onInit},
          {"\nconst person = {\n  firstName: people\n    .filter(person => "
           "person.firstName.startsWith('s'))\n    .map(person => "
           "person.firstName)[0],\n};",
           onInit},
          {"\n() => {\n  const y = foo(y => y);\n};", onInit},
          {"const x = (x => x)();", onInit},
          {"var y = bar || (y => y)();", onInit},
          {"var y = bar && (y => y)();", onInit},
          {"var x = (x => x)((y => y)());", onInit},
          {"const { a = 1 } = (a => {})();", onInit},
          {"\n() => {\n  const y = (y => y)();\n};", onInit},
          {"const [x = y => y] = [].map(y => y);"},
          {"\ntype Foo<A> = 1;\ntype A = 1;", hoistNever},
          {"\ninterface Foo<A> {}\ntype A = 1;", hoistNever},
          {"\ninterface Foo<A> {}\ninterface A {}", hoistNever},
          {"\ntype Foo<A> = 1;\ninterface A {}", hoistNever},
          {"\n{\n  type A = 1;\n}\ntype A = 1;", hoistNever},
          {"\n{\n  interface Foo<A> {}\n}\ntype A = 1;", hoistNever},
          {"\ntype Foo<A> = 1;\ntype A = 1;", hoistFunctions},
          {"\ninterface Foo<A> {}\ntype A = 1;", hoistFunctions},
          {"\ninterface Foo<A> {}\ninterface A {}", hoistFunctions},
          {"\ntype Foo<A> = 1;\ninterface A {}", hoistFunctions},
          {"\n{\n  type A = 1;\n}\ntype A = 1;", hoistFunctions},
          {"\n{\n  interface Foo<A> {}\n}\ntype A = 1;", hoistFunctions},
          {"\nimport type { Foo } from 'bar';\ndeclare module 'bar' {\n  export type Foo "
           "= "
           "string;\n}"},
          {"\nimport type { Foo } from 'bar';\ndeclare module 'bar' {\n  interface Foo "
           "{\n    "
           "x: string;\n  }\n}"},
          {"\nimport { type Foo } from 'bar';\ndeclare module 'bar' {\n  export type Foo "
           "= "
           "string;\n}"},
          {"\nimport { type Foo } from 'bar';\ndeclare module 'bar' {\n  export "
           "interface Foo "
           "{\n    x: string;\n  }\n}"},
          {"\nimport { type Foo } from 'bar';\ndeclare module 'bar' {\n  type Foo = "
           "string;\n}"},
          {"\nimport { type Foo } from 'bar';\ndeclare module 'bar' {\n  interface Foo "
           "{\n    "
           "x: string;\n  }\n}"},
          {"\ndeclare const Object: boolean;", builtins, "baz.d.ts"},
          {"\ndeclare let Array: boolean;", builtins, "baz.d.ts"},
          {"\ndeclare var Map: boolean;", builtins, "baz.d.ts"},
          {"\ndeclare class Set {}", builtins, "baz.d.ts"},
          {"\ndeclare enum Symbol {}", builtins, "baz.d.ts"},
          {"\ndeclare namespace JSON {}", builtins, "baz.d.ts"},
      },
      {
          {"\ntype T = 1;\n{\n  type T = 2;\n}",
           {{"noShadow",
             4,
             8,
             4,
             9,
             "'T' is already declared in the upper scope on line 2 column 6."}}},
          {"\ntype T = 1;\nfunction foo<T>(arg: T) {}", {{"noShadow", 3, 14, 3, 15}}},
          {"\nfunction foo<T>() {\n  return function <T>() {};\n}",
           {{"noShadow", 3, 20, 3, 21}}},
          {"\ntype T = string;\nfunction foo<T extends (arg: any) => void>(arg: T) {}",
           {{"noShadow", 3, 14, 3, 15}}},
          {"\nenum A {\n  A,\n  B,\n}",
           {{"noEnumShadow",
             3,
             3,
             3,
             4,
             "Enum members are added to the enum scope, so references to 'A' in enum "
             "member "
             "initializers resolve to this member instead of the declaration in the "
             "upper "
             "scope on line 2 column 6."}}},
          {"\nenum A {\n  B = 2,\n}\nenum A {\n  A = 1,\n}",
           {{"noEnumShadow",
             6,
             3,
             6,
             4,
             "Enum members are added to the enum scope, so references to 'A' in enum "
             "member "
             "initializers resolve to this member instead of the declaration in the "
             "upper "
             "scope on line 2 column 6."}}},
          {"\nconst x = 1;\n{\n  type x = string;\n}",
           {{"noShadow",
             4,
             8,
             4,
             9,
             "'x' is already declared in the upper scope on line 2 column 7."}},
           nullptr,
           typeValue},
          {"\nconst test = 1;\ntype Fn = (test: string) => typeof test;",
           {{"noShadow", 3, 12, 3, 24}},
           nullptr,
           fnParam},
          {"\nconst arg = 0;\ninterface Test {\n  (arg: string): typeof arg;\n}",
           {{"noShadow", 4, 4, 4, 15}},
           nullptr,
           fnParam},
          {"\nconst arg = 0;\ninterface Test {\n  p1(arg: string): typeof arg;\n}",
           {{"noShadow", 4, 6, 4, 17}},
           nullptr,
           fnParam},
          {"\nconst arg = 0;\ndeclare function test(arg: string): typeof arg;",
           {{"noShadow", 3, 23, 3, 34}},
           nullptr,
           fnParam},
          {"\nconst arg = 0;\ndeclare const test: (arg: string) => typeof arg;",
           {{"noShadow", 3, 22, 3, 33}},
           nullptr,
           fnParam},
          {"\nconst arg = 0;\ndeclare class Test {\n  p1(arg: string): typeof arg;\n}",
           {{"noShadow", 4, 6, 4, 17}},
           nullptr,
           fnParam},
          {"\nconst arg = 0;\ndeclare const Test: {\n  new (arg: string): typeof "
           "arg;\n};",
           {{"noShadow", 4, 8, 4, 19}},
           nullptr,
           fnParam},
          {"\nconst arg = 0;\ntype Bar = new (arg: number) => typeof arg;",
           {{"noShadow", 3, 17, 3, 28}},
           nullptr,
           fnParam},
          {"\nconst arg = 0;\ndeclare namespace Lib {\n  function test(arg: string): "
           "typeof "
           "arg;\n}",
           {{"noShadow", 4, 17, 4, 28}},
           nullptr,
           fnParam},
          {"\nimport type { foo } from './foo';\nfunction doThing(foo: number) {}",
           {{"noShadow",
             3,
             18,
             3,
             29,
             "'foo' is already declared in the upper scope on line 2 column 15."}},
           nullptr,
           typeValue},
          {"\nimport { type foo } from './foo';\nfunction doThing(foo: number) {}",
           {{"noShadow", 3, 18, 3, 29}},
           nullptr,
           typeValue},
          {"\nimport { foo } from './foo';\nfunction doThing(foo: number, bar: number) "
           "{}",
           {{"noShadow",
             3,
             18,
             3,
             29,
             "'foo' is already declared in the upper scope on line 2 column 10."}},
           nullptr,
           keepTypeValue},
          {"\ninterface Foo {}\ndeclare module 'bar' {\n  export interface Foo {\n    x: "
           "string;\n  }\n}",
           {{"noShadow",
             4,
             20,
             4,
             23,
             "'Foo' is already declared in the upper scope on line 2 column 11."}}},
          {"\nimport type { Foo } from 'bar';\ndeclare module 'baz' {\n  export "
           "interface Foo "
           "{\n    x: string;\n  }\n}",
           {{"noShadow",
             4,
             20,
             4,
             23,
             "'Foo' is already declared in the upper scope on line 2 column 15."}}},
          {"\nimport { type Foo } from 'bar';\ndeclare module 'baz' {\n  export "
           "interface Foo "
           "{\n    x: string;\n  }\n}",
           {{"noShadow", 4, 20, 4, 23}}},
          {"\nlet x = foo((x, y) => {});\nlet y;",
           {{"noShadow",
             2,
             14,
             2,
             15,
             "'x' is already declared in the upper scope on line 2 column 5."},
            {"noShadow",
             2,
             17,
             2,
             18,
             "'y' is already declared in the upper scope on line 3 column 5."}},
           nullptr,
           hoistAll},
          {"\nlet x = foo((x, y) => {});\nlet y;",
           {{"noShadow", 2, 14, 2, 15}},
           nullptr,
           hoistFunctions},
          {"\ntype Foo<A> = 1;\ntype A = 1;",
           {{"noShadow",
             2,
             10,
             2,
             11,
             "'A' is already declared in the upper scope on line 3 column 6."}},
           nullptr,
           hoistTypes},
          {"\ninterface Foo<A> {}\ntype A = 1;",
           {{"noShadow", 2, 15, 2, 16}},
           nullptr,
           hoistTypes},
          {"\ninterface Foo<A> {}\ninterface A {}",
           {{"noShadow",
             2,
             15,
             2,
             16,
             "'A' is already declared in the upper scope on line 3 column 11."}},
           nullptr,
           hoistTypes},
          {"\ntype Foo<A> = 1;\ninterface A {}",
           {{"noShadow", 2, 10, 2, 11}},
           nullptr,
           hoistTypes},
          {"\n{\n  type A = 1;\n}\ntype A = 1;",
           {{"noShadow",
             3,
             8,
             3,
             9,
             "'A' is already declared in the upper scope on line 5 column 6."}},
           nullptr,
           hoistTypes},
          {"\n{\n  interface A {}\n}\ntype A = 1;",
           {{"noShadow", 3, 13, 3, 14}},
           nullptr,
           hoistTypes},
          {"\ntype Foo<A> = 1;\ntype A = 1;",
           {{"noShadow", 2, 10, 2, 11}},
           nullptr,
           hoistAll},
          {"\ninterface Foo<A> {}\ntype A = 1;",
           {{"noShadow", 2, 15, 2, 16}},
           nullptr,
           hoistAll},
          {"\n{\n  interface A {}\n}\ntype A = 1;",
           {{"noShadow", 3, 13, 3, 14}},
           nullptr,
           hoistAll},
          {"\ntype Foo<A> = 1;\ntype A = 1;",
           {{"noShadow", 2, 10, 2, 11}},
           nullptr,
           hoistBoth},
          {"\ninterface Foo<A> {}\ninterface A {}",
           {{"noShadow", 2, 15, 2, 16}},
           nullptr,
           hoistBoth},
          {"\ntype Foo<A> = 1;\ninterface A {}",
           {{"noShadow", 2, 10, 2, 11}},
           nullptr,
           hoistBoth},
          {"\n{\n  type A = 1;\n}\ntype A = 1;",
           {{"noShadow", 3, 8, 3, 9}},
           nullptr,
           hoistBoth},
          {"\n{\n  interface A {}\n}\ntype A = 1;", {{"noShadow", 3, 13, 3, 14}}},
          {"\nfunction foo<T extends (...args: any[]) => any>(fn: T, Object: any[]) {}",
           {{"noShadowGlobal", 2, 56, 2, 69, "'Object' is already a global variable."}},
           nullptr,
           R"([{"builtinGlobals": true, "ignoreTypeValueShadow": false}])"},
          {"\ndeclare const has: (environment: 'dev' | 'prod' | 'test') => "
           "boolean;\nconst fn = "
           "(has: string) => {};",
           {{"noShadow",
             3,
             13,
             3,
             24,
             "'has' is already declared in the upper scope on line 2 column 15."}},
           nullptr,
           builtins,
           "foo.d.ts"},
      });
}

TEST(rules_no_shadow, eslint_cases)
{
  const char *builtins = R"([{"builtinGlobals": true}])";
  const char *hoistAll = R"([{"hoist": "all"}])";
  const char *hoistNever = R"([{"hoist": "never"}])";
  const char *onInit = R"([{"ignoreOnInitialization": true}])";
  test::runRuleTests(
      rules::kNoShadow,
      {
          {"\nvar a = 3;\nfunction b(x) {\n  a++;\n  return x + "
           "a;\n}\nsetTimeout(function () "
           "{\n  b(a);\n}, 0);"},
          {"\n(function () {\n  var doSomething = function doSomething() {};\n  "
           "doSomething();\n})();"},
          {"var a = foo || function a() {};"},
          {"var a = foo ? function a() {} : bar;"},
          {"function foo(a = function a() {}) {}"},
          {"\nvar arguments;\nfunction bar() {}"},
          {"\nvar a = 3;\nvar b = x => {\n  a++;\n  return x + a;\n};\nsetTimeout(() => "
           "{\n  "
           "b(a);\n}, 0);"},
          {"class A {}"},
          {"\nclass A {\n  constructor() {\n    var a;\n  }\n}"},
          {"\n(function () {\n  var A = class A {};\n})();"},
          {"\n{\n  var a;\n}\nvar a;"},
          {"\n{\n  let a;\n}\nlet a;", hoistNever},
          {"\n{\n  let a;\n}\nvar a;", hoistNever},
          {"\n{\n  let a;\n}\nfunction a() {}", hoistNever},
          {"\n{\n  const a = 0;\n}\nconst a = 1;", hoistNever},
          {"\n{\n  const a = 0;\n}\nvar a;", hoistNever},
          {"\n{\n  const a = 0;\n}\nfunction a() {}", hoistNever},
          {"\nfunction foo() {\n  let a;\n}\nlet a;", hoistNever},
          {"\nfunction foo() {\n  let a;\n}\nvar a;", hoistNever},
          {"\nfunction foo() {\n  let a;\n}\nfunction a() {}", hoistNever},
          {"\nfunction foo() {\n  var a;\n}\nlet a;", hoistNever},
          {"\nfunction foo() {\n  var a;\n}\nvar a;", hoistNever},
          {"\nfunction foo() {\n  var a;\n}\nfunction a() {}", hoistNever},
          {"\nfunction foo(a) {}\nlet a;", hoistNever},
          {"\nfunction foo(a) {}\nvar a;", hoistNever},
          {"\nfunction foo(a) {}\nfunction a() {}", hoistNever},
          {"\n{\n  let a;\n}\nlet a;"},
          {"\n{\n  let a;\n}\nvar a;"},
          {"\n{\n  const a = 0;\n}\nconst a = 1;"},
          {"\n{\n  const a = 0;\n}\nvar a;"},
          {"\nfunction foo() {\n  let a;\n}\nlet a;"},
          {"\nfunction foo() {\n  let a;\n}\nvar a;"},
          {"\nfunction foo() {\n  var a;\n}\nlet a;"},
          {"\nfunction foo() {\n  var a;\n}\nvar a;"},
          {"\nfunction foo(a) {}\nlet a;"},
          {"\nfunction foo(a) {}\nvar a;"},
          {"\nfunction foo() {\n  var Object = 0;\n}"},
          {"\nfunction foo() {\n  var top = 0;\n}", builtins},
          {"var top = 0;", builtins},
          // A script's top-level `var` merges with the global, so nothing is shadowed.
          {"var Object = 0;", builtins, "test.js"},
          {"\nfunction foo(cb) {\n  (function (cb) {\n    cb(42);\n  })(cb);\n}",
           R"([{"allow": ["cb"]}])"},
      },
      {
          {"\nfunction a(x) {\n  var b = function c() {\n    var x = 'foo';\n  };\n}",
           {{"noShadow",
             4,
             9,
             4,
             10,
             "'x' is already declared in the upper scope on line 2 column 12."}}},
          {"\nvar a = x => {\n  var b = () => {\n    var x = 'foo';\n  };\n};",
           {{"noShadow",
             4,
             9,
             4,
             10,
             "'x' is already declared in the upper scope on line 2 column 9."}}},
          {"\nfunction a(x) {\n  var b = function () {\n    var x = 'foo';\n  };\n}",
           {{"noShadow", 4, 9, 4, 10}}},
          {"\nvar x = 1;\nfunction a(x) {\n  return ++x;\n}",
           {{"noShadow",
             3,
             12,
             3,
             13,
             "'x' is already declared in the upper scope on line 2 column 5."}}},
          {"\nvar a = 3;\nfunction b() {\n  var a = 10;\n}", {{"noShadow", 4, 7, 4, 8}}},
          {"\nvar a = 3;\nfunction b() {\n  var a = 10;\n}\nsetTimeout(function () {\n  "
           "b();\n}, 0);",
           {{"noShadow", 4, 7, 4, 8}}},
          {"\nvar a = 3;\nfunction b() {\n  var a = 10;\n  var b = "
           "0;\n}\nsetTimeout(function "
           "() {\n  b();\n}, 0);",
           {{"noShadow",
             4,
             7,
             4,
             8,
             "'a' is already declared in the upper scope on line 2 column 5."},
            {"noShadow",
             5,
             7,
             5,
             8,
             "'b' is already declared in the upper scope on line 3 column 10."}}},
          {"\nvar x = 1;\n{\n  let x = 2;\n}", {{"noShadow", 4, 7, 4, 8}}},
          {"\nlet x = 1;\n{\n  const x = 2;\n}", {{"noShadow", 4, 9, 4, 10}}},
          {"\n{\n  let a;\n}\nfunction a() {}",
           {{"noShadow",
             3,
             7,
             3,
             8,
             "'a' is already declared in the upper scope on line 5 column 10."}}},
          {"\n{\n  const a = 0;\n}\nfunction a() {}", {{"noShadow", 3, 9, 3, 10}}},
          {"\nfunction foo() {\n  let a;\n}\nfunction a() {}",
           {{"noShadow", 3, 7, 3, 8}}},
          {"\nfunction foo() {\n  var a;\n}\nfunction a() {}",
           {{"noShadow", 3, 7, 3, 8}}},
          {"\nfunction foo(a) {}\nfunction a() {}",
           {{"noShadow",
             2,
             14,
             2,
             15,
             "'a' is already declared in the upper scope on line 3 column 10."}}},
          {"\n{\n  let a;\n}\nlet a;",
           {{"noShadow",
             3,
             7,
             3,
             8,
             "'a' is already declared in the upper scope on line 5 column 5."}},
           nullptr,
           hoistAll},
          {"\n{\n  let a;\n}\nvar a;", {{"noShadow", 3, 7, 3, 8}}, nullptr, hoistAll},
          {"\n{\n  let a;\n}\nfunction a() {}",
           {{"noShadow", 3, 7, 3, 8}},
           nullptr,
           hoistAll},
          {"\n{\n  const a = 0;\n}\nconst a = 1;",
           {{"noShadow",
             3,
             9,
             3,
             10,
             "'a' is already declared in the upper scope on line 5 column 7."}},
           nullptr,
           hoistAll},
          {"\n{\n  const a = 0;\n}\nvar a;",
           {{"noShadow", 3, 9, 3, 10}},
           nullptr,
           hoistAll},
          {"\n{\n  const a = 0;\n}\nfunction a() {}",
           {{"noShadow", 3, 9, 3, 10}},
           nullptr,
           hoistAll},
          {"\nfunction foo() {\n  let a;\n}\nlet a;",
           {{"noShadow", 3, 7, 3, 8}},
           nullptr,
           hoistAll},
          {"\nfunction foo() {\n  let a;\n}\nvar a;",
           {{"noShadow", 3, 7, 3, 8}},
           nullptr,
           hoistAll},
          {"\nfunction foo() {\n  let a;\n}\nfunction a() {}",
           {{"noShadow", 3, 7, 3, 8}},
           nullptr,
           hoistAll},
          {"\nfunction foo() {\n  var a;\n}\nlet a;",
           {{"noShadow", 3, 7, 3, 8}},
           nullptr,
           hoistAll},
          {"\nfunction foo() {\n  var a;\n}\nvar a;",
           {{"noShadow", 3, 7, 3, 8}},
           nullptr,
           hoistAll},
          {"\nfunction foo() {\n  var a;\n}\nfunction a() {}",
           {{"noShadow", 3, 7, 3, 8}},
           nullptr,
           hoistAll},
          {"\nfunction foo(a) {}\nlet a;",
           {{"noShadow",
             2,
             14,
             2,
             15,
             "'a' is already declared in the upper scope on line 3 column 5."}},
           nullptr,
           hoistAll},
          {"\nfunction foo(a) {}\nvar a;",
           {{"noShadow", 2, 14, 2, 15}},
           nullptr,
           hoistAll},
          {"\nfunction foo(a) {}\nfunction a() {}",
           {{"noShadow", 2, 14, 2, 15}},
           nullptr,
           hoistAll},
          {"\n(function a() {\n  function a() {}\n})();",
           {{"noShadow",
             3,
             12,
             3,
             13,
             "'a' is already declared in the upper scope on line 2 column 11."}}},
          {"\n(function a() {\n  class a {}\n})();", {{"noShadow", 3, 9, 3, 10}}},
          {"\n(function a() {\n  (function a() {});\n})();",
           {{"noShadow", 3, 13, 3, 14}}},
          {"\n(function a() {\n  (class a {});\n})();", {{"noShadow", 3, 10, 3, 11}}},
          {"\n(function () {\n  var a = function (a) {};\n})();",
           {{"noShadow",
             3,
             21,
             3,
             22,
             "'a' is already declared in the upper scope on line 3 column 7."}}},
          {"\n(function () {\n  var a = function () {\n    function a() {}\n  };\n})();",
           {{"noShadow", 4, 14, 4, 15}}},
          {"\n(function () {\n  var a = function () {\n    class a {}\n  };\n})();",
           {{"noShadow", 4, 11, 4, 12}}},
          {"\n(function () {\n  var a = function () {\n    (function a() {});\n  "
           "};\n})();",
           {{"noShadow", 4, 15, 4, 16}}},
          {"\n(function () {\n  var a = function () {\n    (class a {});\n  };\n})();",
           {{"noShadow", 4, 12, 4, 13}}},
          {"\n(function () {\n  var a = class {\n    constructor() {\n      class a {}\n "
           "   "
           "}\n  };\n})();",
           {{"noShadow",
             5,
             13,
             5,
             14,
             "'a' is already declared in the upper scope on line 3 column 7."}}},
          {"\nclass A {\n  constructor() {\n    var A;\n  }\n}",
           {{"noShadow",
             4,
             9,
             4,
             10,
             "'A' is already declared in the upper scope on line 2 column 7."}}},
          {"\n(function a() {\n  function a() {\n    function a() {}\n  }\n})();",
           {{"noShadow",
             3,
             12,
             3,
             13,
             "'a' is already declared in the upper scope on line 2 column 11."},
            {"noShadow",
             4,
             14,
             4,
             15,
             "'a' is already declared in the upper scope on line 3 column 12."}}},
          {"\nfunction foo() {\n  var Object = 0;\n}",
           {{"noShadowGlobal", 3, 7, 3, 13, "'Object' is already a global variable."}},
           nullptr,
           builtins},
          {"var Object = 0;", {{"noShadowGlobal", 1, 5, 1, 11}}, nullptr, builtins},
          {"\nfunction foo(cb) {\n  (function (cb) {\n    cb(42);\n  })(cb);\n}",
           {{"noShadow",
             3,
             14,
             3,
             16,
             "'cb' is already declared in the upper scope on line 2 column 14."}}},
          {"\nconst FooBarComponent = memo(function FooBarComponent() {});",
           {{"noShadow",
             2,
             39,
             2,
             54,
             "'FooBarComponent' is already declared in the upper scope on line 2 column "
             "7."}}},
          {"\nconst FooBarComponent = memo(class FooBarComponent {});",
           {{"noShadow", 2, 36, 2, 51}}},
          {"\nconst FooBarComponent = memo(function FooBarComponent() {});",
           {{"noShadow", 2, 39, 2, 54}},
           nullptr,
           onInit},
          {"\nfunction foo(a = wrap(function a() {})) {}",
           {{"noShadow",
             2,
             32,
             2,
             33,
             "'a' is already declared in the upper scope on line 2 column 14."}}},
          {"\nvar a = 1;\nvar b = function a() {};",
           {{"noShadow",
             3,
             18,
             3,
             19,
             "'a' is already declared in the upper scope on line 2 column 5."}}},
      });
}
