#include "fastlint/rules/rules.h"
#include "testing/rule_tester.h"
#include "testing/test.h"

using namespace fastlint;

TEST(rules_prefer_const, cases)
{
  const char *all = R"([{"destructuring": "all"}])";
  const char *any = R"([{"destructuring": "any"}])";
  const char *ignoreRead = R"([{"ignoreReadBeforeAssign": true}])";
  test::runRuleTests(
      rules::kPreferConst,
      {
          {"var x = 0;"},
          {"let x;"},
          {"let x; { x = 0; } foo(x);"},
          {"let x = 0; x = 1;"},
          {"using resource = fn();"},
          {"await using resource = fn();"},
          {"const x = 0;"},
          {"for (let i = 0, end = 10; i < end; ++i) {}"},
          {"for (let i in [1,2,3]) { i = 0; }"},
          {"for (let x of [1,2,3]) { x = 0; }"},
          {"(function() { var x = 0; })();"},
          {"(function() { let x; })();"},
          {"(function() { let x; { x = 0; } foo(x); })();"},
          {"(function() { let x = 0; x = 1; })();"},
          {"(function() { const x = 0; })();"},
          {"(function() { for (let i = 0, end = 10; i < end; ++i) {} })();"},
          {"(function() { for (let i in [1,2,3]) { i = 0; } })();"},
          {"(function() { for (let x of [1,2,3]) { x = 0; } })();"},
          {"(function(x = 0) { })();"},
          {"let a; while (a = foo());"},
          {"let a; do {} while (a = foo());"},
          {"let a; for (; a = foo(); );"},
          {"let a; for (;; ++a);"},
          {"let a; for (const {b = ++a} in foo());"},
          {"let a; for (const {b = ++a} of foo());"},
          {"let a; for (const x of [1,2,3]) { if (a) {} a = foo(); }"},
          {"let a; for (const x of [1,2,3]) { a = a || foo(); bar(a); }"},
          {"let a; for (const x of [1,2,3]) { foo(++a); }"},
          {"let a; function foo() { if (a) {} a = bar(); }"},
          {"let a; function foo() { a = a || bar(); baz(a); }"},
          {"let a; function foo() { bar(++a); }"},
          {"let id;\nfunction foo() {\n    if (typeof id !== 'undefined') {\n        "
           "return;\n"
           "    }\n    id = setInterval(() => {}, 250);\n}\nfoo();"},
          {"let a; if (true) a = 0; foo(a);"},
          {"(function (a) { let b; ({ a, b } = obj); })();"},
          {"(function (a) { let b; ([ a, b ] = obj); })();"},
          {"var a; { var b; ({ a, b } = obj); }"},
          {"let a; { let b; ({ a, b } = obj); }"},
          {"var a; { var b; ([ a, b ] = obj); }"},
          {"let a; { let b; ([ a, b ] = obj); }"},
          {"let x; { x = 0; foo(x); }"},
          {"(function() { let x; { x = 0; foo(x); } })();"},
          {"let x; for (const a of [1,2,3]) { x = foo(); bar(x); }"},
          {"(function() { let x; for (const a of [1,2,3]) { x = foo(); bar(x); } })();"},
          {"let x; for (x of array) { x; }"},
          {"let {a, b} = obj; b = 0;", all},
          {"let a, b; ({a, b} = obj); b++;", all},
          {"let { name, ...otherStuff } = obj; otherStuff = {};", all},
          {"let predicate; [typeNode.returnType, predicate] = foo();"},
          {"let predicate; [typeNode.returnType, ...predicate] = foo();"},
          {"let predicate; [typeNode.returnType,, predicate] = foo();"},
          {"let predicate; [typeNode.returnType=5, predicate] = foo();"},
          {"let predicate; [[typeNode.returnType=5], predicate] = foo();"},
          {"let predicate; [[typeNode.returnType, predicate]] = foo();"},
          {"let predicate; [typeNode.returnType, [predicate]] = foo();"},
          {"let predicate; [, [typeNode.returnType, predicate]] = foo();"},
          {"let predicate; [, {foo:typeNode.returnType, predicate}] = foo();"},
          {"let predicate; [, {foo:typeNode.returnType, ...predicate}] = foo();"},
          {"let a; const b = {}; ({ a, c: b.c } = func());"},
          {"let x; function foo() { bar(x); } x = 0;", ignoreRead},
          {"const x = [1,2]; let y; [,y] = x; y = 0;"},
          {"const x = [1,2,3]; let y, z; [y,,z] = x; y = 0; z = 0;"},
          {"class C { static { let a = 1; a = 2; } }"},
          {"class C { static { let a; a = 1; a = 2; } }"},
          {"let a; class C { static { a = 1; } }"},
          {"class C { static { let a; if (foo) { a = 1; } } }"},
          {"class C { static { let a; if (foo) a = 1; } }"},
          {"class C { static { let a, b; if (foo) { ({ a, b } = foo); } } }"},
          {"class C { static { let a, b; if (foo) ({ a, b } = foo); } }"},
          {"class C { static { a; } } let a = 1; ", ignoreRead},
          {"class C { static { () => a; let a = 1; } };", ignoreRead},
          {"declare let x: number;"},
      },
      {
          {"let x = 1; foo(x);",
           {{"useConst", 1, 5, 1, 6, "'x' is never reassigned. Use 'const' instead."}},
           "const x = 1; foo(x);"},
          {"for (let i in [1,2,3]) { foo(i); }",
           {{"useConst"}},
           "for (const i in [1,2,3]) { foo(i); }"},
          {"for (let x of [1,2,3]) { foo(x); }",
           {{"useConst"}},
           "for (const x of [1,2,3]) { foo(x); }"},
          {"let [x = -1, y] = [1,2]; y = 0;", {{"useConst", 1, 6, 1, 7}}},
          {"let {a: x = -1, b: y} = {a:1,b:2}; y = 0;", {{"useConst", 1, 9, 1, 10}}},
          {"(function() { let x = 1; foo(x); })();",
           {{"useConst"}},
           "(function() { const x = 1; foo(x); })();"},
          {"(function() { for (let i in [1,2,3]) { foo(i); } })();",
           {{"useConst"}},
           "(function() { for (const i in [1,2,3]) { foo(i); } })();"},
          {"(function() { for (let x of [1,2,3]) { foo(x); } })();",
           {{"useConst"}},
           "(function() { for (const x of [1,2,3]) { foo(x); } })();"},
          {"(function() { let [x = -1, y] = [1,2]; y = 0; })();", {{"useConst"}}},
          {"let f = (function() { let g = x; })(); f = 1;",
           {{"useConst", 1, 27, 1, 28}},
           "let f = (function() { const g = x; })(); f = 1;"},
          {"(function() { let {a: x = -1, b: y} = {a:1,b:2}; y = 0; })();",
           {{"useConst"}}},
          {"let x = 0; { let x = 1; foo(x); } x = 0;",
           {{"useConst", 1, 18, 1, 19}},
           "let x = 0; { const x = 1; foo(x); } x = 0;"},
          {"for (let i = 0; i < 10; ++i) { let x = 1; foo(x); }",
           {{"useConst"}},
           "for (let i = 0; i < 10; ++i) { const x = 1; foo(x); }"},
          {"for (let i in [1,2,3]) { let x = 1; foo(x); }",
           {{"useConst", 1, 10}, {"useConst", 1, 30}},
           "for (const i in [1,2,3]) { const x = 1; foo(x); }"},
          {"var foo = function() {\n    for (const b of c) {\n       let a;\n       a = "
           "1;\n"
           "   }\n};",
           {{"useConst", 4, 8, 4, 9}}},
          {"var foo = function() {\n    for (const b of c) {\n       let a;\n       ({a} "
           "= 1);\n"
           "   }\n};",
           {{"useConst", 4, 10, 4, 11}}},
          {"let x; x = 0;", {{"useConst", 1, 8}}},
          {"switch (a) { case 0: let x; x = 0; }", {{"useConst", 1, 29}}},
          {"(function() { let x; x = 1; })();", {{"useConst", 1, 22}}},
          {"let {a = 0, b} = obj; b = 0; foo(a, b);",
           {{"useConst", 1, 6, 1, 7}},
           nullptr,
           any},
          {"let {a: {b, c}} = {a: {b: 1, c: 2}}; b = 3;",
           {{"useConst", 1, 13, 1, 14}},
           nullptr,
           any},
          {"let {a: {b, c}} = {a: {b: 1, c: 2}}",
           {{"useConst"}, {"useConst"}},
           "const {a: {b, c}} = {a: {b: 1, c: 2}}",
           all},
          {"let a, b; ({a = 0, b} = obj); b = 0; foo(a, b);",
           {{"useConst", 1, 13, 1, 14}},
           nullptr,
           any},
          {"let {a = 0, b} = obj; foo(a, b);",
           {{"useConst"}, {"useConst"}},
           "const {a = 0, b} = obj; foo(a, b);",
           all},
          {"let [a] = [1]", {{"useConst"}}, "const [a] = [1]"},
          {"let {a} = obj", {{"useConst"}}, "const {a} = obj"},
          {"let a, b; ({a = 0, b} = obj); foo(a, b);",
           {{"useConst", 1, 13}, {"useConst", 1, 20}},
           nullptr,
           all},
          {"let {a = 0, b} = obj, c = a; b = a;",
           {{"useConst", 1, 6}, {"useConst", 1, 23}},
           nullptr,
           any},
          {"let {a = 0, b} = obj, c = a; b = a;", {{"useConst", 1, 23}}, nullptr, all},
          {"let { name, ...otherStuff } = obj; otherStuff = {};",
           {{"useConst", 1, 7}},
           nullptr,
           any},
          {"let x; function foo() { bar(x); } x = 0;", {{"useConst", 1, 5}}},
          {"let { foo, bar } = baz;",
           {{"useConst"}, {"useConst"}},
           "const { foo, bar } = baz;"},
          {"const x = [1,2]; let [,y] = x;",
           {{"useConst"}},
           "const x = [1,2]; const [,y] = x;"},
          {"const x = [1,2,3]; let [y,,z] = x;",
           {{"useConst"}, {"useConst"}},
           "const x = [1,2,3]; const [y,,z] = x;"},
          {"let predicate; [, {foo:returnType, predicate}] = foo();",
           {{"useConst",
             0,
             0,
             0,
             0,
             "'predicate' is never reassigned. Use 'const' instead."}}},
          {"let predicate; [, {foo:returnType, predicate}, ...bar ] = foo();",
           {{"useConst"}}},
          {"let predicate; [, {foo:returnType, ...predicate} ] = foo();", {{"useConst"}}},
          {"let x = 'x', y = 'y';",
           {{"useConst", 1, 5}, {"useConst", 1, 14}},
           "const x = 'x', y = 'y';"},
          {"let x = 'x', y = 'y'; x = 1", {{"useConst", 1, 14}}},
          {"let x = 1, y = 'y'; let z = 1;",
           {{"useConst"}, {"useConst"}, {"useConst"}},
           "const x = 1, y = 'y'; const z = 1;"},
          {"let { a, b, c} = obj; let { x, y, z} = anotherObj; x = 2;",
           {{"useConst"}, {"useConst"}, {"useConst"}, {"useConst"}, {"useConst"}},
           "const { a, b, c} = obj; let { x, y, z} = anotherObj; x = 2;"},
          {"let x = 'x', y = 'y'; function someFunc() { let a = 1, b = 2; foo(a, b) }",
           {{"useConst"}, {"useConst"}, {"useConst"}, {"useConst"}},
           "const x = 'x', y = 'y'; function someFunc() { const a = 1, b = 2; foo(a, b) "
           "}"},
          {"let someFunc = () => { let a = 1, b = 2; foo(a, b) }",
           {{"useConst"}, {"useConst"}, {"useConst"}},
           "const someFunc = () => { const a = 1, b = 2; foo(a, b) };"},
          {"let {a, b} = c, d;", {{"useConst"}, {"useConst"}}},
          {"let {a, b, c} = {}, e, f;", {{"useConst"}, {"useConst"}, {"useConst"}}},
          {"function a() {\nlet foo = 0,\n  bar = 1;\nfoo = 1;\n}\nfunction b() {\nlet "
           "foo = 0,\n"
           "  bar = 2;\nfoo = 2;\n}",
           {{"useConst", 3, 3}, {"useConst", 8, 3}}},
          {"let a = 1; class C { static { a; } }",
           {{"useConst"}},
           "const a = 1; class C { static { a; } }"},
          {"class C { static { a; } } let a = 1;",
           {{"useConst"}},
           "class C { static { a; } } const a = 1;"},
          {"class C { static { let a = 1; } }",
           {{"useConst"}},
           "class C { static { const a = 1; } }"},
          {"class C { static { if (foo) { let a = 1; } } }",
           {{"useConst"}},
           "class C { static { if (foo) { const a = 1; } } }"},
          {"class C { static { let a = 1; if (foo) { a; } } }",
           {{"useConst"}},
           "class C { static { const a = 1; if (foo) { a; } } }"},
          {"class C { static { if (foo) { let a; a = 1; } } }", {{"useConst"}}},
          {"class C { static { let a; a = 1; } }", {{"useConst", 1, 27}}},
          {"class C { static { let { a, b } = foo; } }",
           {{"useConst"}, {"useConst"}},
           "class C { static { const { a, b } = foo; } }"},
          {"class C { static { let a, b; ({ a, b } = foo); } }",
           {{"useConst"}, {"useConst"}}},
          {"class C { static { let a; let b; ({ a, b } = foo); } }",
           {{"useConst"}, {"useConst"}}},
          {"class C { static { let a; a = 0; console.log(a); } }", {{"useConst"}}},
          {"let { itemId, list } = {},\nobj = [],\ntotal = 0;\ntotal = 9;\n"
           "console.log(itemId, list, obj, total);",
           {{"useConst", 1, 7}, {"useConst", 1, 15}, {"useConst", 2, 1}},
           nullptr,
           R"([{"destructuring": "any", "ignoreReadBeforeAssign": true}])"},
          {"let x: number = 1; foo(x);", {{"useConst"}}, "const x: number = 1; foo(x);"},
      });
}
