#include "fastlint/rules/rules.h"
#include "testing/rule_tester.h"
#include "testing/test.h"

using namespace fastlint;

TEST(rules_no_self_assign, cases)
{
  const char *noProps = R"([{"props": false}])";
  test::runRuleTests(
      rules::kNoSelfAssign,
      {
          {"var a = a"},
          {"a = b"},
          {"a += a"},
          {"a = +a"},
          {"a = [a]"},
          {"a &= a"},
          {"a = {a}"},
          {"let a = a"},
          {"const a = a"},
          {"[a] = a"},
          {"[a = 1] = [a]"},
          {"[a, b] = [b, a]"},
          {"[a,, b] = [, b, a]"},
          {"[x, a] = [...x, a]"},
          {"[...a] = [...a, 1]"},
          {"[a, ...b] = [0, ...b, 1]"},
          {"[a, b] = {a, b}"},
          {"({a} = a)"},
          {"({a = 1} = {a})"},
          {"({a: b} = {a})"},
          {"({a} = {a: b})"},
          {"({a} = {a() {}})"},
          {"({a} = {[a]: a})"},
          {"({[a]: b} = {[a]: b})"},
          {"({'foo': a, 1: a} = {'bar': a, 2: a})"},
          {"({a, ...b} = {a, ...b})"},
          {"a.b = a.c"},
          {"a.b = c.b"},
          {"a.b = a[b]"},
          {"a[b] = a.b"},
          {"a.b().c = a.b().c"},
          {"b().c = b().c"},
          {"a.null = a[null]"},
          {"a[b + 1] = a[b + 1]"},
          {"a.b = a.b", noProps},
          {"a.b.c = a.b.c", noProps},
          {"a[b] = a[b]", noProps},
          {"a['b'] = a['b']", noProps},
          {"a[\n    'b'\n] = a[\n    'b'\n]", noProps},
          {"this.x = this.y"},
          {"this.x = this.x", noProps},
          {"class C { #field; foo() { this['#field'] = this.#field; } }"},
          {"class C { #field; foo() { this.#field = this['#field']; } }"},
      },
      {
          {"a = a", {{"selfAssignment", 1, 5, 1, 6, "'a' is assigned to itself."}}},
          {"[a] = [a]", {{"selfAssignment"}}},
          {"[a, b] = [a, b]", {{"selfAssignment"}, {"selfAssignment"}}},
          {"[a, b] = [a, c]", {{"selfAssignment"}}},
          {"[a, b] = [, b]", {{"selfAssignment"}}},
          {"[a, ...b] = [a, ...b]", {{"selfAssignment"}, {"selfAssignment"}}},
          {"[[a], {b}] = [[a], {b}]", {{"selfAssignment"}, {"selfAssignment"}}},
          {"({a} = {a})", {{"selfAssignment"}}},
          {"({a: b} = {a: b})", {{"selfAssignment"}}},
          {"({'a': b} = {'a': b})", {{"selfAssignment"}}},
          {"({a: b} = {'a': b})", {{"selfAssignment"}}},
          {"({'a': b} = {a: b})", {{"selfAssignment"}}},
          {"({1: b} = {1: b})", {{"selfAssignment"}}},
          {"({1: b} = {'1': b})", {{"selfAssignment"}}},
          {"({'1': b} = {1: b})", {{"selfAssignment"}}},
          {"({['a']: b} = {a: b})", {{"selfAssignment"}}},
          {"({'a': b} = {[`a`]: b})", {{"selfAssignment"}}},
          {"({1: b} = {[1]: b})", {{"selfAssignment"}}},
          {"({a, b} = {a, b})", {{"selfAssignment"}, {"selfAssignment"}}},
          {"({a, b} = {b, a})", {{"selfAssignment"}, {"selfAssignment"}}},
          {"({a, b} = {c, a})", {{"selfAssignment"}}},
          {"({a: {b}, c: [d]} = {a: {b}, c: [d]})",
           {{"selfAssignment"}, {"selfAssignment"}}},
          {"({a, b} = {a, ...x, b})", {{"selfAssignment"}}},
          {"a.b = a.b",
           {{"selfAssignment", 1, 7, 1, 10, "'a.b' is assigned to itself."}}},
          {"a.b.c = a.b.c",
           {{"selfAssignment", 0, 0, 0, 0, "'a.b.c' is assigned to itself."}}},
          {"a[b] = a[b]",
           {{"selfAssignment", 0, 0, 0, 0, "'a[b]' is assigned to itself."}}},
          {"a['b'] = a['b']", {{"selfAssignment"}}},
          {"a[\n    'b'\n] = a[\n    'b'\n]",
           {{"selfAssignment", 0, 0, 0, 0, "'a['b']' is assigned to itself."}}},
          {"this.x = this.x",
           {{"selfAssignment", 0, 0, 0, 0, "'this.x' is assigned to itself."}}},
          {"a.b = a.b", {{"selfAssignment"}}, nullptr, R"([{"props": true}])"},
          {"a &&= a", {{"selfAssignment"}}},
          {"a ||= a", {{"selfAssignment"}}},
          {"a ??= a", {{"selfAssignment"}}},
          {"class C { #field; foo() { this.#field = this.#field; } }",
           {{"selfAssignment", 0, 0, 0, 0, "'this.#field' is assigned to itself."}}},
      });
}
