import fs from "node:fs";
import path from "node:path";
import type { CommandModule } from "yargs";
import { info, step } from "./lib/log.ts";
import { repoRoot } from "./lib/paths.ts";

interface Args {
  name: string;
  out?: string;
  selector: string;
}

/** `no-await-in-loop` -> `noAwaitInLoop`, the export a config imports. */
function camel(name: string): string {
  return name.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

/** The starter rule module: a working rule that reports on every `selector`
 * node, for the author to narrow. It imports the `fastlint` package surface. */
function template(name: string, selector: string): string {
  return `// The ${name} rule. Generated by \`node make.ts new-rule\`; edit freely.

import { NodeKind } from "fastlint";
import type { Rule } from "fastlint";

export const ${camel(name)}: Rule = {
  name: "${name}",
  messages: {
    unexpected: "Describe the problem here.",
  },
  create(context) {
    return {
      ${selector}(node) {
        // Narrow with node.is(NodeKind.${selector}) and read the typed view.
        void NodeKind;
        context.report({ node, messageId: "unexpected" });
      },
    };
  },
};
`;
}

export const command: CommandModule<object, Args> = {
  command : "new-rule <name>",
  describe: "scaffold a TypeScript rule module (create-fastlint-rule)",
  builder: (yargs) =>
    yargs
      .positional("name", {
        type        : "string",
        describe    : "the rule name, in kebab-case",
        demandOption: true,
      })
      .option("out", {
        type    : "string",
        describe: "output file (default <name>.ts in the current directory)",
      })
      .option("selector", {
        type    : "string",
        default : "Identifier",
        describe: "the node kind the rule visits",
      }) as never,
  handler: (argv) => {
    const name = argv.name;
    if (!/^[a-z][a-z0-9-]*$/.test(name)) {
      throw new Error(`rule name must be kebab-case: ${name}`);
    }
    const out = argv.out
      ? path.resolve(argv.out)
      : path.join(process.cwd(), `${name}.ts`);
    if (fs.existsSync(out)) {
      throw new Error(`${path.relative(repoRoot, out)} already exists`);
    }
    fs.mkdirSync(path.dirname(out), { recursive: true });
    fs.writeFileSync(out, template(name, argv.selector));
    step(`wrote ${path.relative(repoRoot, out)}`);
    info(
      `add it to your fastlint.config.ts:\n  import { ${camel(name)} } from "./${name}.ts";`
    );
  },
};
