import fs from "node:fs";
import path from "node:path";
import type { CommandModule } from "yargs";
import { color, info, step } from "./lib/log.ts";
import { repoRoot } from "./lib/paths.ts";

interface Args {
  name?: string;
  out?: string;
  selector: string;
  init: boolean;
}

/** `no-await-in-loop` -> `noAwaitInLoop`, the export a config imports. */
function camel(name: string): string {
  return name.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}

/** The starter rule module: a working rule that reports on every `selector`
 * node, for the author to narrow. It imports the `fastlint` package surface. */
function ruleTemplate(name: string, selector: string): string {
  return `// The ${name} rule. Generated by \`node make.ts new-rule\`; edit freely.

import { NodeKind } from "fastlint";
import type { Rule } from "fastlint";

export const ${camel(name)}: Rule = {
  name: "${name}",
  messages: {
    unexpected: "Describe the problem here.",
  },
  create(context) {
    return {
      ${selector}(node) {
        // Narrow with node.is(NodeKind.${selector}) and read the typed view.
        void NodeKind;
        context.report({ node, messageId: "unexpected" });
      },
    };
  },
};
`;
}

/** The starter config: an empty rule list the author fills in. `new-rule <name>`
 * prints the import line to add here. */
function configTemplate(): string {
  return `// fastlint.config.ts. Generated by \`node make.ts new-rule --init\`.
// Scaffold a rule with \`node make.ts new-rule <name>\`, then import it here and
// add it to the list.

import { defineConfig } from "fastlint";

export default defineConfig({
  rules: [],
});
`;
}

/** Resolves an output path against the current directory, with `fallback` as the
 * default basename, and refuses to overwrite. */
function resolveOut(out: string | undefined, fallback: string): string {
  const resolved = out ? path.resolve(out) : path.join(process.cwd(), fallback);
  if (fs.existsSync(resolved)) {
    throw new Error(`${path.relative(repoRoot, resolved)} already exists`);
  }
  return resolved;
}

/** Writes `content` to `out`, creating parent directories, and reports it. */
function write(out: string, content: string): void {
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, content);
  step(`wrote ${path.relative(repoRoot, out)}`);
}

export const command: CommandModule<object, Args> = {
  command : "new-rule [name]",
  describe: "scaffold a TypeScript rule or a config (create-fastlint-rule)",
  builder: (yargs) =>
    yargs
      .positional("name", {
        type    : "string",
        describe: "rule name in kebab-case; omit it when passing --init",
      })
      .option("init", {
        type    : "boolean",
        default : false,
        describe: "write a starter fastlint.config.ts instead of a rule",
      })
      .option("selector", {
        type    : "string",
        default : "Identifier",
        describe: "node kind the rule's visitor fires on (a NodeKind name)",
      })
      .option("out", {
        type    : "string",
        describe: "output file; defaults to <name>.ts, or fastlint.config.ts with --init",
      })
      .example("$0 new-rule no-empty-catch", "scaffold a rule visiting Identifier nodes")
      .example(
        "$0 new-rule no-empty-catch --selector CatchClause",
        "scaffold a rule visiting CatchClause nodes"
      )
      .example(
        "$0 new-rule --init",
        "write a starter fastlint.config.ts in this directory"
      )
      .epilogue(
        `See ${color.cyan("docs/plugins.md")} for the rule and config reference.`
      ) as never,
  handler: (argv) => {
    if (argv.init) {
      if (argv.name) {
        throw new Error("pass a rule <name> or --init, not both");
      }
      const out = resolveOut(argv.out, "fastlint.config.ts");
      write(out, configTemplate());
      info(
        "scaffold rules with `node make.ts new-rule <name>`, then import and list them here"
      );
      return;
    }

    const name = argv.name;
    if (!name) {
      throw new Error("provide a rule <name>, or pass --init to create a config");
    }
    if (!/^[a-z][a-z0-9-]*$/.test(name)) {
      throw new Error(`rule name must be kebab-case: ${name}`);
    }
    const out = resolveOut(argv.out, `${name}.ts`);
    write(out, ruleTemplate(name, argv.selector));
    info(
      `add it to your fastlint.config.ts:\n  import { ${camel(name)} } from "./${name}.ts";`
    );
  },
};
