// Reads the flag enums the installed typescript package ships under dist/enums/ and writes
// source/fastlint/tsgo/generated/enums.h. `node make.ts gen-tsgo-enums` runs it; `--check`
// reports whether the header is stale.

import fs from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..");
const require = createRequire(import.meta.url);

/** Enums the type layer reads; each becomes a namespace of `constexpr uint32_t`. */
const ENUMS = [
  "typeFlags",
  "objectFlags",
  "symbolFlags",
  "elementFlags",
  "signatureFlags",
  "syntaxKind",
];

interface EnumTable {
  name: string;
  members: { name: string; value: number }[];
}

function typescriptDir(): string {
  return path.dirname(require.resolve("typescript/package.json"));
}

async function loadEnum(file: string): Promise<EnumTable> {
  const mod = (await import(
    pathToFileURL(path.join(typescriptDir(), "dist", "enums", `${file}.enum.js`)).href
  )) as Record<string, Record<string, unknown>>;
  const exportName = Object.keys(mod)[0];
  if (!exportName) throw new Error(`${file}.enum.js exports nothing`);
  const table = mod[exportName]!;
  // Reverse-mapped enum objects hold both name -> value and value -> name.
  const members: { name: string; value: number }[] = [];
  const seen = new Set<string>();
  for (const [key, value] of Object.entries(table)) {
    if (typeof value !== "number" || seen.has(key)) continue;
    seen.add(key);
    members.push({ name: key, value });
  }
  return { name: exportName, members };
}

function cppName(name: string): string {
  // A member such as `Import` is a C++ keyword risk only for a handful of names.
  const reserved = new Set([
    "Default",
    "Delete",
    "Export",
    "New",
    "This",
    "Void",
    "Null",
  ]);
  return reserved.has(name) ? `${name}_` : name;
}

export async function emitHeader(): Promise<string> {
  const pkg = JSON.parse(
    fs.readFileSync(path.join(typescriptDir(), "package.json"), "utf8")
  ) as {
    version: string;
  };
  const lines: string[] = [
    "// Generated by `node make.ts gen-tsgo-enums` from the typescript package's dist/enums/.",
    `// typescript ${pkg.version}. DO NOT EDIT.`,
    "#pragma once",
    "",
    "#include <cstdint>",
    "",
    "namespace fastlint::tsgo {",
    "",
    `constexpr const char *kEnumsFromVersion = "${pkg.version}";`,
  ];
  for (const file of ENUMS) {
    const table = await loadEnum(file);
    lines.push("", `namespace ${table.name} {`);
    for (const { name, value } of table.members) {
      lines.push(`constexpr uint32_t ${cppName(name)} = ${value >>> 0}u;`);
    }
    lines.push(`} // namespace ${table.name}`);
  }
  lines.push("", "} // namespace fastlint::tsgo", "");
  return lines.join("\n");
}

export interface GenerateResult {
  changed: string[];
}

export async function generate(check: boolean): Promise<GenerateResult> {
  const file = path.join(repoRoot, "source", "fastlint", "tsgo", "generated", "enums.h");
  const content = await emitHeader();
  const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : undefined;
  const changed: string[] = [];
  if (current !== content) {
    changed.push(path.relative(repoRoot, file));
    if (!check) {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, content);
    }
  }
  return { changed };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  const result = await generate(check);
  for (const file of result.changed) console.log(`${check ? "stale" : "wrote"} ${file}`);
  if (check && result.changed.length > 0) process.exit(1);
}
