# Run in script mode after a test executable is built. Runs it with `--list`
# and writes an `add_test()` per suite into CTEST_FILE, which the directory
# includes through TEST_INCLUDE_FILES. Discovery has to happen after the link
# step, so it cannot be done inline at configure time.

execute_process(
  COMMAND "${TEST_EXECUTABLE}" --list --all --no-color
  OUTPUT_VARIABLE listing
  RESULT_VARIABLE status
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

set(content "# generated by cmake/DiscoverTests.cmake\n")

if(NOT status EQUAL 0)
  set(content "${content}add_test(${TEST_NAME}.discovery_failed \"${TEST_EXECUTABLE}\" --list)\n")
else()
  string(REPLACE "\n" ";" lines "${listing}")
  set(suites "")
  foreach(line IN LISTS lines)
    string(STRIP "${line}" line)
    if(line STREQUAL "")
      continue()
    endif()
    # `suite.name [tag] [tag]` -> `suite`
    string(REGEX REPLACE "\\..*$" "" suite "${line}")
    list(APPEND suites "${suite}")
  endforeach()
  list(REMOVE_DUPLICATES suites)

  foreach(suite IN LISTS suites)
    # ctest reads this file itself, and only understands the legacy positional
    # add_test signature.
    set(content "${content}add_test(${TEST_NAME}.${suite} \"${TEST_EXECUTABLE}\" --filter \"${suite}.*\" --all)\n")
    set(content "${content}set_tests_properties(${TEST_NAME}.${suite} PROPERTIES WORKING_DIRECTORY \"${TEST_WORKING_DIR}\")\n")
  endforeach()
endif()

file(WRITE "${CTEST_FILE}" "${content}")
